export const listofnews = [
    { id: '1', img: 'assets/images/new1.jpg', title: 'Past Lives - vòng lặp nhân duyên', shortinfo: 'Trailer "Past Lives", khởi chiếu trong nước ngày 29/9. Sau sáu ngày ra mắt, phim thu hơn 4,8 tỷ đồng. Video: CGV', info: 'Tác phẩm là phim đầu tay của đạo diễn Celine Song, chia thành ba mốc thời gian. 24 năm trước, Nora (Greta Lee đóng) và Hae Sung (Yoo Teo) là học sinh 12 tuổi, thân thiết với nhau như tri kỷ. Một ngày, Nora ngỏ lời hẹn hò với Hae Sung trước khi cùng gia đình di cư sang Canada. Chính buổi hẹn hò "tuổi mới lớn" này đã ăn sâu vào trí nhớ của Hae Sung suốt nhiều năm.Sau 12 năm ở nước ngoài, Nora sang New York (Mỹ) ổn định cuộc sống, theo đuổi ước mơ trở thành một nhà văn. Trong khi đó, Hae Sung vừa mới xuất ngũ và chuẩn bị những kế hoạch cho tương lai. Một ngày, cả hai tình cờ tìm thấy nhau trên mạng xã hội, họ cùng nhau trò chuyện thâu đêm suốt sáng. Tuy nhiên, khoảng cách địa lý và sự khác biệt về quan điểm sống đã khiến Nora và Hae Sung rời xa nhau. Hiện, Nora kết hôn với Arthur (John Magaro) còn Hae Sung vừa chia tay bạn gái. Chuyến đi chơi New York của Hae Sung đã cho anh và Nora cơ hội gặp nhau sau 24 năm.Đạo diễn Celine Song sắp đặt những sự kiện trong tác phẩm để ẩn dụ cho "inyeon", nghĩa là những cuộc gặp gỡ đều do nhân duyên sắp đặt. Trong phim, có hai khoảnh khắc "inyeon" xuất hiện, một là khi Nora và Hae Sung bên nhau thời thơ ấu và lúc Nora bắt đầu cuộc sống hôn nhân với Arthur.Mạch phim chậm rãi, diễn biến theo vòng lặp: Gặp nhau, chia xa, rồi gặp lại nhau và tiếp tục chia xa. Mối tình của Nora và Hae Sung quanh quẩn ở việc trò chuyện và ngầm hiểu suy nghĩ của nhau. Ở đó, không ai có cơ hội tỏ tình hay nói lời yêu. Khi Hae Sung gặp lại Nora ở New York, mọi thứ giữa hai người chỉ là những kỷ niệm trong quá khứ.' },
    { id: '2', img: 'assets/images/new2.jpg', title: 'Đạo diễn Đặng Nhật Minh đoạt giải Bùi Xuân Phái', shortinfo: 'Đạo diễn Đặng Nhật Minh trong buổi trao giải chiều 5/10 ở Hà Nội. Ảnh: Hà Thu', info: 'Đạo diễn Đặng Nhật Minh (85 tuổi) được trao Giải thưởng Lớn Bùi Xuân Phái với những bộ phim nổi tiếng về Hà Nội.Nghệ sĩ cùng gia đình tới dự lễ trao giải chiều 5/10 ở Hà Nội. Ông được ban tổ chức vinh danh với các tác phẩm điện ảnh phản ánh lịch sử, thấm đẫm tình yêu Hà Nội, cụ thể là chùm ba phim Hà Nội mùa đông năm 46, Mùa ổi và Hoa nhài.Ông phát biểu: "Hà Nội là tình yêu của tôi, là nơi tôi gắn bó hơn 60 năm cuộc đời. Giải thưởng hôm nay là sự ghi nhận cho tình yêu đó trong tôi, thể hiện qua những phim mà tôi đã làm về mảnh đất này. Giải thưởng càng quý giá hơn khi tôi nhận được nó khi tuổi đã cao, trong những ngày tháng 10 đáng nhớ". Ông cảm ơn ban tổ chức, ban giám khảo, những cộng sự làm phim của mình.' },
    { id: '3', img: 'assets/images/new3.jpg', title: 'David Beckham khen Messi trong phim tài liệu', shortinfo: 'Trailer "Messi Meets America", Beckham xuất hiện từ giây thứ 14. Video: Apple TV', info: 'Trailer ra mắt hôm 3/10, có đoạn ghi lại khoảnh khắc Beckham ôm Messi sau khi đội Inter Miami vô địch Leagues Cup 2023 hồi tháng 8. Messi nói: "Hạnh phúc của tôi là được chơi bóng. Và bây giờ tôi có thể tiếp tục niềm đam mê tại Mỹ".Trên People, đại diện nhà sản xuất nói loạt phim hứa hẹn mang đến cái nhìn sâu sắc về giai đoạn mới nhất trong sự nghiệp của Messi: Chiến thắng Leagues Cup 2023 và trận ra mắt giải bóng đá nhà nghề Mỹ - Major League Soccer (MLS). Cầu thủ còn kể về cuộc sống ở Mỹ và kỷ niệm với câu lạc bộ Inter Miami.' },
]
export const slides = [
    { title: "Thiện Ác Đối Đầu", src: "image/1.jpg", Eng: "The equalizer 3 (2023)" },
    { title: "Nhiệm Vụ Bất Khả Thi", src: "image/1.jpg", Eng: "Mission: Impossible Dead Reckoning Part One (2023)" },
    { title: "The Nun 2", src: "image/1.jpg", Eng: "The Nun 2 (2023)" },
    { title: "Biệt Đội Đánh Thuê", src: "image/1.jpg", Eng: "Expend4Ble (2023)" }

];